/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as CoopRouteImport } from './routes/coop'
import { Route as DataRouteImport } from './routes/data'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as MatchRouteImport } from './routes/match'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ModesRouteImport } from './routes/modes'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StatisticsRouteImport } from './routes/statistics'
import { Route as DeckDeckIdRouteImport } from './routes/deck.$deckId'
import { Route as DevContentAuditRouteImport } from './routes/dev.content-audit'
import { Route as TrialsIndexRouteImport } from './routes/trials.index'
import { Route as TrialsMatchRouteImport } from './routes/trials.match'
import { Route as TutorialIndexRouteImport } from './routes/tutorial.index'
import { Route as TutorialLessonIdRouteImport } from './routes/tutorial.$lessonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const CoopRoute = CoopRouteImport.update({
  id: '/coop',
  path: '/coop',
  getParentRoute: () => rootRouteImport,
} as any)
const DataRoute = DataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ModesRoute = ModesRouteImport.update({
  id: '/modes',
  path: '/modes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StatisticsRoute = StatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckDeckIdRoute = DeckDeckIdRouteImport.update({
  id: '/deck/$deckId',
  path: '/deck/$deckId',
  getParentRoute: () => rootRouteImport,
} as any)
const DevContentAuditRoute = DevContentAuditRouteImport.update({
  id: '/dev/content-audit',
  path: '/dev/content-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialsIndexRoute = TrialsIndexRouteImport.update({
  id: '/trials/',
  path: '/trials/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialsMatchRoute = TrialsMatchRouteImport.update({
  id: '/trials/match',
  path: '/trials/match',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialIndexRoute = TutorialIndexRouteImport.update({
  id: '/tutorial/',
  path: '/tutorial/',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialLessonIdRoute = TutorialLessonIdRouteImport.update({
  id: '/tutorial/$lessonId',
  path: '/tutorial/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/achievements': typeof AchievementsRoute
  '/collection': typeof CollectionRoute
  '/coop': typeof CoopRoute
  '/data': typeof DataRoute
  '/decks': typeof DecksRoute
  '/learn': typeof LearnRoute
  '/match': typeof MatchRoute
  '/menu': typeof MenuRoute
  '/modes': typeof ModesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/dev/content-audit': typeof DevContentAuditRoute
  '/trials/match': typeof TrialsMatchRoute
  '/tutorial/$lessonId': typeof TutorialLessonIdRoute
  '/trials/': typeof TrialsIndexRoute
  '/tutorial/': typeof TutorialIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/achievements': typeof AchievementsRoute
  '/collection': typeof CollectionRoute
  '/coop': typeof CoopRoute
  '/data': typeof DataRoute
  '/decks': typeof DecksRoute
  '/learn': typeof LearnRoute
  '/match': typeof MatchRoute
  '/menu': typeof MenuRoute
  '/modes': typeof ModesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/dev/content-audit': typeof DevContentAuditRoute
  '/trials/match': typeof TrialsMatchRoute
  '/tutorial/$lessonId': typeof TutorialLessonIdRoute
  '/trials': typeof TrialsIndexRoute
  '/tutorial': typeof TutorialIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/achievements': typeof AchievementsRoute
  '/collection': typeof CollectionRoute
  '/coop': typeof CoopRoute
  '/data': typeof DataRoute
  '/decks': typeof DecksRoute
  '/learn': typeof LearnRoute
  '/match': typeof MatchRoute
  '/menu': typeof MenuRoute
  '/modes': typeof ModesRoute
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/statistics': typeof StatisticsRoute
  '/deck/$deckId': typeof DeckDeckIdRoute
  '/dev/content-audit': typeof DevContentAuditRoute
  '/trials/match': typeof TrialsMatchRoute
  '/tutorial/$lessonId': typeof TutorialLessonIdRoute
  '/trials/': typeof TrialsIndexRoute
  '/tutorial/': typeof TutorialIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/achievements'
    | '/collection'
    | '/coop'
    | '/data'
    | '/decks'
    | '/learn'
    | '/match'
    | '/menu'
    | '/modes'
    | '/profile'
    | '/settings'
    | '/statistics'
    | '/deck/$deckId'
    | '/dev/content-audit'
    | '/trials/match'
    | '/tutorial/$lessonId'
    | '/trials/'
    | '/tutorial/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/achievements'
    | '/collection'
    | '/coop'
    | '/data'
    | '/decks'
    | '/learn'
    | '/match'
    | '/menu'
    | '/modes'
    | '/profile'
    | '/settings'
    | '/statistics'
    | '/deck/$deckId'
    | '/dev/content-audit'
    | '/trials/match'
    | '/tutorial/$lessonId'
    | '/trials'
    | '/tutorial'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/achievements'
    | '/collection'
    | '/coop'
    | '/data'
    | '/decks'
    | '/learn'
    | '/match'
    | '/menu'
    | '/modes'
    | '/profile'
    | '/settings'
    | '/statistics'
    | '/deck/$deckId'
    | '/dev/content-audit'
    | '/trials/match'
    | '/tutorial/$lessonId'
    | '/trials/'
    | '/tutorial/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AchievementsRoute: typeof AchievementsRoute
  CollectionRoute: typeof CollectionRoute
  CoopRoute: typeof CoopRoute
  DataRoute: typeof DataRoute
  DecksRoute: typeof DecksRoute
  LearnRoute: typeof LearnRoute
  MatchRoute: typeof MatchRoute
  MenuRoute: typeof MenuRoute
  ModesRoute: typeof ModesRoute
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  StatisticsRoute: typeof StatisticsRoute
  DeckDeckIdRoute: typeof DeckDeckIdRoute
  DevContentAuditRoute: typeof DevContentAuditRoute
  TrialsMatchRoute: typeof TrialsMatchRoute
  TutorialLessonIdRoute: typeof TutorialLessonIdRoute
  TrialsIndexRoute: typeof TrialsIndexRoute
  TutorialIndexRoute: typeof TutorialIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coop': {
      id: '/coop'
      path: '/coop'
      fullPath: '/coop'
      preLoaderRoute: typeof CoopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data': {
      id: '/data'
      path: '/data'
      fullPath: '/data'
      preLoaderRoute: typeof DataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modes': {
      id: '/modes'
      path: '/modes'
      fullPath: '/modes'
      preLoaderRoute: typeof ModesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statistics': {
      id: '/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof StatisticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck/$deckId': {
      id: '/deck/$deckId'
      path: '/deck/$deckId'
      fullPath: '/deck/$deckId'
      preLoaderRoute: typeof DeckDeckIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/content-audit': {
      id: '/dev/content-audit'
      path: '/dev/content-audit'
      fullPath: '/dev/content-audit'
      preLoaderRoute: typeof DevContentAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trials/': {
      id: '/trials/'
      path: '/trials'
      fullPath: '/trials/'
      preLoaderRoute: typeof TrialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trials/match': {
      id: '/trials/match'
      path: '/trials/match'
      fullPath: '/trials/match'
      preLoaderRoute: typeof TrialsMatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial/': {
      id: '/tutorial/'
      path: '/tutorial'
      fullPath: '/tutorial/'
      preLoaderRoute: typeof TutorialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial/$lessonId': {
      id: '/tutorial/$lessonId'
      path: '/tutorial/$lessonId'
      fullPath: '/tutorial/$lessonId'
      preLoaderRoute: typeof TutorialLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AchievementsRoute: AchievementsRoute,
  CollectionRoute: CollectionRoute,
  CoopRoute: CoopRoute,
  DataRoute: DataRoute,
  DecksRoute: DecksRoute,
  LearnRoute: LearnRoute,
  MatchRoute: MatchRoute,
  MenuRoute: MenuRoute,
  ModesRoute: ModesRoute,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  StatisticsRoute: StatisticsRoute,
  DeckDeckIdRoute: DeckDeckIdRoute,
  DevContentAuditRoute: DevContentAuditRoute,
  TrialsMatchRoute: TrialsMatchRoute,
  TutorialLessonIdRoute: TutorialLessonIdRoute,
  TrialsIndexRoute: TrialsIndexRoute,
  TutorialIndexRoute: TutorialIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
